version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      production-deps:
        dependency-type: 'production'
        update-types: ['patch', 'minor']
      dev-deps:
        dependency-type: 'development'
        update-types: ['patch', 'minor']
    ignore:
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react-dom'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 10
